### ISSUE TITLE
Service the service instance, not patient profile

### ISSUE THREAD

**Issue by elirehema** [ospic/platform#134]
****IDEA****
 I'm always frustrated when i want to implement finalization of patient service. Let say the patient  checked today, get registered and assigned to specific specialist and after diagnosis and other required procedures and patient paid for service we want to mark a this patient service as **DONE** but keep our patient records or infos for the next time service.

The problem arise if we mark a patient profile as DONE and remove it from the queue of patients next time we need to query for patient to reapear to mark him/her as active again.

Also if we link all patient diagnosis, treatment and payment reports in the same patient profile it may become difficult to recognize which service does this patient get for specific date. The idea came in if we want to get all patient infos for the specific day we have to query by date. The problem rise what if the patient get admitted let say for 5 days how are we going to keep this records and make sure the patient pay for the admission service. 

The idea came in we have to specify how long the patient is going to be admitted and record it in his/her payment infos. But at the same time physician may device to discharge patient before those days or elongate the admission period while we have already recorded the transaction of specific date.

**SOLUTION**
The solution of this was to create a patient service instance. Once the patient is recorded and we want to start servicing him/her we should create the patient service instance linked to specific patient which will carry all required information e.g services he has received during this instance periods, diagnosis and laboratory reports if any, medications, date, admissions and its costs if any. The next time the patient shows up we need just to start a new service instance. So instead of recording the all patient diagnosises, admissions, medication costs etc separatelly this instance will carry all of those information.  

**ALTENATIVES**
The room of altenatives is open for anyone to rise s/he's altenative. Welcome

**Additional context**
This was just an idea. If you have anything to add or to reduce you can just shout it out and you will make us feel happy.

**Comment by deogemini** [comment]
In my view to save a patient, we will need to have one instance of
categories where patients will be saved by category so when a patient will
come again to the hospital will be seen as already active since the name of
patients will be in one of the categories in the system

**Comment by elirehema** [comment]
@deogemini can you give an example of those categories ?

**Comment by deogemini** [comment]
Yes, I can.
But these categories will after first admission of the patient in the
hospital so you may categories patients by their health problems
Or groups of diseases
Example
Patient with less care
Patient with communicable-disease
Patient with non communicable-disease
Patient needs much care
Patient needs specialists with special appointments
Patient with common health problems in country like malaria in Tanzania

**Comment by deogemini** [comment]
Yes, I can.

**Comment by elirehema** [comment]
@deogemini i think you are missing my key point. The solution was to resolve a patient profile from contain a lot of data relations like, admission histories, admission visits, diagnoses. If you try to check the current databse schema, you may see that the patient has connection to admissions, diagnoses assigned physician etc, which may affect perfomance when the patient have many admissions, visits, diag etc. 
![image](https://user-images.githubusercontent.com/29277048/102996769-b4de1000-4534-11eb-83b9-74a4543ae77f.png)


So the solution was to have a service instance e.g table `patient_service` which has relation to the patient. So when we want to check patient medical history we just check the specific service instance which will have all infos.

**Comment by deogemini** [comment]
thanks for that is the proper solution, so the table "patient_service"
might have  following columns "patient_id", "patient_name", "diagnoses_id",
"admission_in",
"contacts_id"

**Comment by elirehema** [comment]
Yes except for contacts which will stii remain in patient table
